openapi: "3.1.1"
info:
  title: Example Todo App
  version: "0.1.8"

servers:
  - url: http://localhost:5000
    description: Development server

paths:
  /api/todos:
    get:
      operationId: getTodos
      security:
        - AccessToken: []
      responses:
        "200":
          description: OK
        "500":
          description: server error

    post:
      operationId: createTodo
      security:
        - AccessToken: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Int32"
      responses:
        "200":
          description: OK
        "500":
          description: server error

components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
    RefreshToken:
      type: apiKey
      in: header
      name: X-Refresh-Token

  schemas:
    Int32:
      type: integer
      format: int32

    Int64:
      type: integer
      format: int64

    Uint32:
      type: integer
      format: int32
      minimum: 0
      maximum: 1000

    Uint64:
      type: integer
      format: int64
      minimum: 0
      maximum: 1000

    Float32:
      type: number
      format: single

    Float64:
      type: number
      format: double

    Text:
      type: string

    Blob:
      type: string
      format: binary

    Bool:
      type: boolean

    IntArray:
      type: array
      items:
        type: integer
