package components

type BaseType string

const (
	BASETYPE_STRING    BaseType = "BASETYPE_STRING"
	BASETYPE_INT       BaseType = "BASETYPE_INT"
	BASETYPE_UINT      BaseType = "BASETYPE_UINT"
	BASETYPE_FLOAT     BaseType = "BASETYPE_FLOAT"
	BASETYPE_BOOL      BaseType = "BASETYPE_BOOL"
	BASETYPE_BLOB      BaseType = "BASETYPE_BLOB"
	BASETYPE_UNDEFINED BaseType = "BASETYPE_UNDEFINED"
)
